require "rake/testtask"

Rake::TestTask.new do |t|
  t.libs << "tests"
  t.test_files = FileList['tests/*_test.rb']
  t.verbose = true
  t.ruby_opts = %w(-W1)
end

task :default do
  Rake::Task[:test].invoke
end
